import nextra from 'nextra'

const withNextra = nextra({
  defaultShowCopyCode: true,
  // Nextra 4 searches with Pagefind, which indexes the *built* HTML — so the
  // index is generated by the `postbuild` script, not by this option. Without
  // that step the search box loads `/_pagefind/pagefind.js` and 404s.
  // Pagefind has no code-block toggle; `codeblocks` was the v3 flexsearch API.
  search: { codeblocks: false },
})

export default withNextra({
  reactStrictMode: true,
  // Hide the Next.js dev-mode "N" indicator (dev-only diagnostic, never shipped).
  devIndicators: false,
})
